// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/proto/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_UNSPECIFIED ConfigType = 0
	ConfigType_CONFIG_TYPE_WHITELIST   ConfigType = 1
	ConfigType_CONFIG_TYPE_ROUTING     ConfigType = 2
	ConfigType_CONFIG_TYPE_USERS       ConfigType = 3
	ConfigType_CONFIG_TYPE_ECH_KEYS    ConfigType = 4
	ConfigType_CONFIG_TYPE_EGRESS_IPS  ConfigType = 5
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "CONFIG_TYPE_UNSPECIFIED",
		1: "CONFIG_TYPE_WHITELIST",
		2: "CONFIG_TYPE_ROUTING",
		3: "CONFIG_TYPE_USERS",
		4: "CONFIG_TYPE_ECH_KEYS",
		5: "CONFIG_TYPE_EGRESS_IPS",
	}
	ConfigType_value = map[string]int32{
		"CONFIG_TYPE_UNSPECIFIED": 0,
		"CONFIG_TYPE_WHITELIST":   1,
		"CONFIG_TYPE_ROUTING":     2,
		"CONFIG_TYPE_USERS":       3,
		"CONFIG_TYPE_ECH_KEYS":    4,
		"CONFIG_TYPE_EGRESS_IPS":  5,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_control_control_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_api_proto_control_control_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{0}
}

type WatchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id identifies the calling gateway/dns/egress node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// config_version is the last version the node has. The controller sends
	// all updates newer than this. Use 0 for a full sync.
	ConfigVersion uint64 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *WatchConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *WatchConfigRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type ConfigUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing version number.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Which configuration section changed.
	ConfigType ConfigType `protobuf:"varint,2,opt,name=config_type,json=configType,proto3,enum=control.ConfigType" json:"config_type,omitempty"`
	// Serialized payload (one of the oneof fields below).
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ConfigUpdate_Whitelist
	//	*ConfigUpdate_Routing
	//	*ConfigUpdate_Users
	//	*ConfigUpdate_EchKeys
	//	*ConfigUpdate_EgressIps
	Payload       isConfigUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_api_proto_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigUpdate) GetConfigType() ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *ConfigUpdate) GetPayload() isConfigUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConfigUpdate) GetWhitelist() *WhitelistConfig {
	if x != nil {
		if x, ok := x.Payload.(*ConfigUpdate_Whitelist); ok {
			return x.Whitelist
		}
	}
	return nil
}

func (x *ConfigUpdate) GetRouting() *RoutingConfig {
	if x != nil {
		if x, ok := x.Payload.(*ConfigUpdate_Routing); ok {
			return x.Routing
		}
	}
	return nil
}

func (x *ConfigUpdate) GetUsers() *UserList {
	if x != nil {
		if x, ok := x.Payload.(*ConfigUpdate_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *ConfigUpdate) GetEchKeys() *ECHKeyConfig {
	if x != nil {
		if x, ok := x.Payload.(*ConfigUpdate_EchKeys); ok {
			return x.EchKeys
		}
	}
	return nil
}

func (x *ConfigUpdate) GetEgressIps() *EgressIPList {
	if x != nil {
		if x, ok := x.Payload.(*ConfigUpdate_EgressIps); ok {
			return x.EgressIps
		}
	}
	return nil
}

type isConfigUpdate_Payload interface {
	isConfigUpdate_Payload()
}

type ConfigUpdate_Whitelist struct {
	Whitelist *WhitelistConfig `protobuf:"bytes,10,opt,name=whitelist,proto3,oneof"`
}

type ConfigUpdate_Routing struct {
	Routing *RoutingConfig `protobuf:"bytes,11,opt,name=routing,proto3,oneof"`
}

type ConfigUpdate_Users struct {
	Users *UserList `protobuf:"bytes,12,opt,name=users,proto3,oneof"`
}

type ConfigUpdate_EchKeys struct {
	EchKeys *ECHKeyConfig `protobuf:"bytes,13,opt,name=ech_keys,json=echKeys,proto3,oneof"`
}

type ConfigUpdate_EgressIps struct {
	EgressIps *EgressIPList `protobuf:"bytes,14,opt,name=egress_ips,json=egressIps,proto3,oneof"`
}

func (*ConfigUpdate_Whitelist) isConfigUpdate_Payload() {}

func (*ConfigUpdate_Routing) isConfigUpdate_Payload() {}

func (*ConfigUpdate_Users) isConfigUpdate_Payload() {}

func (*ConfigUpdate_EchKeys) isConfigUpdate_Payload() {}

func (*ConfigUpdate_EgressIps) isConfigUpdate_Payload() {}

type WhitelistConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domains with "." prefix are suffix matches; otherwise exact.
	Domains       []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistConfig) Reset() {
	*x = WhitelistConfig{}
	mi := &file_api_proto_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistConfig) ProtoMessage() {}

func (x *WhitelistConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistConfig.ProtoReflect.Descriptor instead.
func (*WhitelistConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *WhitelistConfig) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type RoutingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*EgressNodeProto     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Rules         []*RoutingRuleProto    `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingConfig) Reset() {
	*x = RoutingConfig{}
	mi := &file_api_proto_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingConfig) ProtoMessage() {}

func (x *RoutingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingConfig.ProtoReflect.Descriptor instead.
func (*RoutingConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingConfig) GetNodes() []*EgressNodeProto {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RoutingConfig) GetRules() []*RoutingRuleProto {
	if x != nil {
		return x.Rules
	}
	return nil
}

type EgressNodeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // "host:port"; empty = direct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressNodeProto) Reset() {
	*x = EgressNodeProto{}
	mi := &file_api_proto_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressNodeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressNodeProto) ProtoMessage() {}

func (x *EgressNodeProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressNodeProto.ProtoReflect.Descriptor instead.
func (*EgressNodeProto) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *EgressNodeProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EgressNodeProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RoutingRuleProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Match:
	//
	//	*RoutingRuleProto_Domain
	//	*RoutingRuleProto_Cidr
	//	*RoutingRuleProto_Geoip
	//	*RoutingRuleProto_IsDefault
	Match         isRoutingRuleProto_Match `protobuf_oneof:"match"`
	EgressNode    string                   `protobuf:"bytes,10,opt,name=egress_node,json=egressNode,proto3" json:"egress_node,omitempty"` // name reference into EgressNodeProto.name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRuleProto) Reset() {
	*x = RoutingRuleProto{}
	mi := &file_api_proto_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRuleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRuleProto) ProtoMessage() {}

func (x *RoutingRuleProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRuleProto.ProtoReflect.Descriptor instead.
func (*RoutingRuleProto) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *RoutingRuleProto) GetMatch() isRoutingRuleProto_Match {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *RoutingRuleProto) GetDomain() string {
	if x != nil {
		if x, ok := x.Match.(*RoutingRuleProto_Domain); ok {
			return x.Domain
		}
	}
	return ""
}

func (x *RoutingRuleProto) GetCidr() *CIDRMatch {
	if x != nil {
		if x, ok := x.Match.(*RoutingRuleProto_Cidr); ok {
			return x.Cidr
		}
	}
	return nil
}

func (x *RoutingRuleProto) GetGeoip() *GeoIPMatch {
	if x != nil {
		if x, ok := x.Match.(*RoutingRuleProto_Geoip); ok {
			return x.Geoip
		}
	}
	return nil
}

func (x *RoutingRuleProto) GetIsDefault() bool {
	if x != nil {
		if x, ok := x.Match.(*RoutingRuleProto_IsDefault); ok {
			return x.IsDefault
		}
	}
	return false
}

func (x *RoutingRuleProto) GetEgressNode() string {
	if x != nil {
		return x.EgressNode
	}
	return ""
}

type isRoutingRuleProto_Match interface {
	isRoutingRuleProto_Match()
}

type RoutingRuleProto_Domain struct {
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3,oneof"` // "*.example.com" or "example.com"
}

type RoutingRuleProto_Cidr struct {
	Cidr *CIDRMatch `protobuf:"bytes,2,opt,name=cidr,proto3,oneof"`
}

type RoutingRuleProto_Geoip struct {
	Geoip *GeoIPMatch `protobuf:"bytes,3,opt,name=geoip,proto3,oneof"`
}

type RoutingRuleProto_IsDefault struct {
	IsDefault bool `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3,oneof"`
}

func (*RoutingRuleProto_Domain) isRoutingRuleProto_Match() {}

func (*RoutingRuleProto_Cidr) isRoutingRuleProto_Match() {}

func (*RoutingRuleProto_Geoip) isRoutingRuleProto_Match() {}

func (*RoutingRuleProto_IsDefault) isRoutingRuleProto_Match() {}

type CIDRMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidrs         []string               `protobuf:"bytes,1,rep,name=cidrs,proto3" json:"cidrs,omitempty"` // e.g. "142.250.0.0/15"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIDRMatch) Reset() {
	*x = CIDRMatch{}
	mi := &file_api_proto_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIDRMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIDRMatch) ProtoMessage() {}

func (x *CIDRMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIDRMatch.ProtoReflect.Descriptor instead.
func (*CIDRMatch) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *CIDRMatch) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

type GeoIPMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []string               `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"` // ISO 3166-1 alpha-2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoIPMatch) Reset() {
	*x = GeoIPMatch{}
	mi := &file_api_proto_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIPMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIPMatch) ProtoMessage() {}

func (x *GeoIPMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoIPMatch.ProtoReflect.Descriptor instead.
func (*GeoIPMatch) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *GeoIPMatch) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProto           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_api_proto_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *UserList) GetUsers() []*UserProto {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`   // SHA256(user_id+":"+salt)[:12]
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"` // optional bearer token
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProto) Reset() {
	*x = UserProto{}
	mi := &file_api_proto_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProto) ProtoMessage() {}

func (x *UserProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProto.ProtoReflect.Descriptor instead.
func (*UserProto) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{9}
}

func (x *UserProto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProto) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UserProto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserProto) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UserProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ECHKeyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded current private key.
	CurrentPrivateKeyPem []byte `protobuf:"bytes,1,opt,name=current_private_key_pem,json=currentPrivateKeyPem,proto3" json:"current_private_key_pem,omitempty"`
	CurrentConfigId      uint32 `protobuf:"varint,2,opt,name=current_config_id,json=currentConfigId,proto3" json:"current_config_id,omitempty"`
	// PEM-encoded previous private key (may be empty during first deployment).
	PreviousPrivateKeyPem []byte `protobuf:"bytes,3,opt,name=previous_private_key_pem,json=previousPrivateKeyPem,proto3" json:"previous_private_key_pem,omitempty"`
	PreviousConfigId      uint32 `protobuf:"varint,4,opt,name=previous_config_id,json=previousConfigId,proto3" json:"previous_config_id,omitempty"`
	// Serialized ECHConfigList for DNS to serve.
	EchConfigList []byte `protobuf:"bytes,5,opt,name=ech_config_list,json=echConfigList,proto3" json:"ech_config_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECHKeyConfig) Reset() {
	*x = ECHKeyConfig{}
	mi := &file_api_proto_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECHKeyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECHKeyConfig) ProtoMessage() {}

func (x *ECHKeyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECHKeyConfig.ProtoReflect.Descriptor instead.
func (*ECHKeyConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{10}
}

func (x *ECHKeyConfig) GetCurrentPrivateKeyPem() []byte {
	if x != nil {
		return x.CurrentPrivateKeyPem
	}
	return nil
}

func (x *ECHKeyConfig) GetCurrentConfigId() uint32 {
	if x != nil {
		return x.CurrentConfigId
	}
	return 0
}

func (x *ECHKeyConfig) GetPreviousPrivateKeyPem() []byte {
	if x != nil {
		return x.PreviousPrivateKeyPem
	}
	return nil
}

func (x *ECHKeyConfig) GetPreviousConfigId() uint32 {
	if x != nil {
		return x.PreviousConfigId
	}
	return 0
}

func (x *ECHKeyConfig) GetEchConfigList() []byte {
	if x != nil {
		return x.EchConfigList
	}
	return nil
}

type EgressIPList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway IPs that egress nodes should allow.
	Ips           []string `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	Cidrs         []string `protobuf:"bytes,2,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressIPList) Reset() {
	*x = EgressIPList{}
	mi := &file_api_proto_control_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressIPList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressIPList) ProtoMessage() {}

func (x *EgressIPList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressIPList.ProtoReflect.Descriptor instead.
func (*EgressIPList) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{11}
}

func (x *EgressIPList) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *EgressIPList) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

type TrafficBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Records       []*TrafficRecord       `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficBatch) Reset() {
	*x = TrafficBatch{}
	mi := &file_api_proto_control_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBatch) ProtoMessage() {}

func (x *TrafficBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBatch.ProtoReflect.Descriptor instead.
func (*TrafficBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{12}
}

func (x *TrafficBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TrafficBatch) GetRecords() []*TrafficRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type TrafficRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Egress        string                 `protobuf:"bytes,4,opt,name=egress,proto3" json:"egress,omitempty"`
	BytesUp       int64                  `protobuf:"varint,5,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown     int64                  `protobuf:"varint,6,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // unix seconds
	EndTime       int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // unix seconds
	EchSuccess    bool                   `protobuf:"varint,9,opt,name=ech_success,json=echSuccess,proto3" json:"ech_success,omitempty"`
	ErrorType     string                 `protobuf:"bytes,10,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRecord) Reset() {
	*x = TrafficRecord{}
	mi := &file_api_proto_control_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRecord) ProtoMessage() {}

func (x *TrafficRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRecord.ProtoReflect.Descriptor instead.
func (*TrafficRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{13}
}

func (x *TrafficRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrafficRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TrafficRecord) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *TrafficRecord) GetEgress() string {
	if x != nil {
		return x.Egress
	}
	return ""
}

func (x *TrafficRecord) GetBytesUp() int64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *TrafficRecord) GetBytesDown() int64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

func (x *TrafficRecord) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TrafficRecord) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TrafficRecord) GetEchSuccess() bool {
	if x != nil {
		return x.EchSuccess
	}
	return false
}

func (x *TrafficRecord) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int64                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"` // total records accepted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_api_proto_control_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{14}
}

func (x *ReportAck) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // optional bearer token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProto             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUserResponse) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{18}
}

func (x *ListUsersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProto           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{19}
}

func (x *ListUsersResponse) GetUsers() []*UserProto {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Fields to update. Only non-empty fields are applied.
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Optional: only overwrites Active when explicitly set.
	Active        *bool `protobuf:"varint,4,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateUserRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProto             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateUserResponse) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{23}
}

type AuthUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hex hash extracted from outer SNI or DoH path.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Optional bearer token for double auth.
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{24}
}

func (x *AuthUserRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AuthUserRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *UserProto             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{25}
}

func (x *AuthUserResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthUserResponse) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

type DNSAuditBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Records       []*DNSAuditRecord      `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSAuditBatch) Reset() {
	*x = DNSAuditBatch{}
	mi := &file_api_proto_control_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSAuditBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSAuditBatch) ProtoMessage() {}

func (x *DNSAuditBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSAuditBatch.ProtoReflect.Descriptor instead.
func (*DNSAuditBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{26}
}

func (x *DNSAuditBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DNSAuditBatch) GetRecords() []*DNSAuditRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type DNSAuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	QueryType     string                 `protobuf:"bytes,3,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"` // "A", "AAAA", "HTTPS", etc.
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSAuditRecord) Reset() {
	*x = DNSAuditRecord{}
	mi := &file_api_proto_control_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSAuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSAuditRecord) ProtoMessage() {}

func (x *DNSAuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSAuditRecord.ProtoReflect.Descriptor instead.
func (*DNSAuditRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{27}
}

func (x *DNSAuditRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DNSAuditRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DNSAuditRecord) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *DNSAuditRecord) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DNSAuditRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DNSAuditAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int64                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSAuditAck) Reset() {
	*x = DNSAuditAck{}
	mi := &file_api_proto_control_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSAuditAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSAuditAck) ProtoMessage() {}

func (x *DNSAuditAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSAuditAck.ProtoReflect.Descriptor instead.
func (*DNSAuditAck) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{28}
}

func (x *DNSAuditAck) GetReceived() int64 {
	if x != nil {
		return x.Received
	}
	return 0
}

type TrafficQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // optional filter
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                         // optional filter
	Egress        string                 `protobuf:"bytes,3,opt,name=egress,proto3" json:"egress,omitempty"`                         // optional filter
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // unix seconds
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficQueryRequest) Reset() {
	*x = TrafficQueryRequest{}
	mi := &file_api_proto_control_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficQueryRequest) ProtoMessage() {}

func (x *TrafficQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficQueryRequest.ProtoReflect.Descriptor instead.
func (*TrafficQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{29}
}

func (x *TrafficQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrafficQueryRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TrafficQueryRequest) GetEgress() string {
	if x != nil {
		return x.Egress
	}
	return ""
}

func (x *TrafficQueryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TrafficQueryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type TrafficQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*TrafficSummary      `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficQueryResponse) Reset() {
	*x = TrafficQueryResponse{}
	mi := &file_api_proto_control_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficQueryResponse) ProtoMessage() {}

func (x *TrafficQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficQueryResponse.ProtoReflect.Descriptor instead.
func (*TrafficQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{30}
}

func (x *TrafficQueryResponse) GetSummaries() []*TrafficSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type TrafficSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Egress        string                 `protobuf:"bytes,3,opt,name=egress,proto3" json:"egress,omitempty"`
	BytesUp       int64                  `protobuf:"varint,4,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown     int64                  `protobuf:"varint,5,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	Count         int64                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"` // number of connections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficSummary) Reset() {
	*x = TrafficSummary{}
	mi := &file_api_proto_control_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSummary) ProtoMessage() {}

func (x *TrafficSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSummary.ProtoReflect.Descriptor instead.
func (*TrafficSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_control_control_proto_rawDescGZIP(), []int{31}
}

func (x *TrafficSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrafficSummary) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TrafficSummary) GetEgress() string {
	if x != nil {
		return x.Egress
	}
	return ""
}

func (x *TrafficSummary) GetBytesUp() int64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *TrafficSummary) GetBytesDown() int64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

func (x *TrafficSummary) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_control_control_proto protoreflect.FileDescriptor

const file_api_proto_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/control/control.proto\x12\acontrol\"T\n" +
	"\x12WatchConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\"\xee\x02\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x124\n" +
	"\vconfig_type\x18\x02 \x01(\x0e2\x13.control.ConfigTypeR\n" +
	"configType\x128\n" +
	"\twhitelist\x18\n" +
	" \x01(\v2\x18.control.WhitelistConfigH\x00R\twhitelist\x122\n" +
	"\arouting\x18\v \x01(\v2\x16.control.RoutingConfigH\x00R\arouting\x12)\n" +
	"\x05users\x18\f \x01(\v2\x11.control.UserListH\x00R\x05users\x122\n" +
	"\bech_keys\x18\r \x01(\v2\x15.control.ECHKeyConfigH\x00R\aechKeys\x126\n" +
	"\n" +
	"egress_ips\x18\x0e \x01(\v2\x15.control.EgressIPListH\x00R\tegressIpsB\t\n" +
	"\apayload\"+\n" +
	"\x0fWhitelistConfig\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"p\n" +
	"\rRoutingConfig\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.control.EgressNodeProtoR\x05nodes\x12/\n" +
	"\x05rules\x18\x02 \x03(\v2\x19.control.RoutingRuleProtoR\x05rules\"?\n" +
	"\x0fEgressNodeProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xce\x01\n" +
	"\x10RoutingRuleProto\x12\x18\n" +
	"\x06domain\x18\x01 \x01(\tH\x00R\x06domain\x12(\n" +
	"\x04cidr\x18\x02 \x01(\v2\x12.control.CIDRMatchH\x00R\x04cidr\x12+\n" +
	"\x05geoip\x18\x03 \x01(\v2\x13.control.GeoIPMatchH\x00R\x05geoip\x12\x1f\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bH\x00R\tisDefault\x12\x1f\n" +
	"\vegress_node\x18\n" +
	" \x01(\tR\n" +
	"egressNodeB\a\n" +
	"\x05match\"!\n" +
	"\tCIDRMatch\x12\x14\n" +
	"\x05cidrs\x18\x01 \x03(\tR\x05cidrs\"*\n" +
	"\n" +
	"GeoIPMatch\x12\x1c\n" +
	"\tcountries\x18\x01 \x03(\tR\tcountries\"4\n" +
	"\bUserList\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.control.UserProtoR\x05users\"\x99\x01\n" +
	"\tUserProto\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x80\x02\n" +
	"\fECHKeyConfig\x125\n" +
	"\x17current_private_key_pem\x18\x01 \x01(\fR\x14currentPrivateKeyPem\x12*\n" +
	"\x11current_config_id\x18\x02 \x01(\rR\x0fcurrentConfigId\x127\n" +
	"\x18previous_private_key_pem\x18\x03 \x01(\fR\x15previousPrivateKeyPem\x12,\n" +
	"\x12previous_config_id\x18\x04 \x01(\rR\x10previousConfigId\x12&\n" +
	"\x0fech_config_list\x18\x05 \x01(\fR\rechConfigList\"6\n" +
	"\fEgressIPList\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\x12\x14\n" +
	"\x05cidrs\x18\x02 \x03(\tR\x05cidrs\"Y\n" +
	"\fTrafficBatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\arecords\x18\x02 \x03(\v2\x16.control.TrafficRecordR\arecords\"\xa9\x02\n" +
	"\rTrafficRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06egress\x18\x04 \x01(\tR\x06egress\x12\x19\n" +
	"\bbytes_up\x18\x05 \x01(\x03R\abytesUp\x12\x1d\n" +
	"\n" +
	"bytes_down\x18\x06 \x01(\x03R\tbytesDown\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x12\x1f\n" +
	"\vech_success\x18\t \x01(\bR\n" +
	"echSuccess\x12\x1d\n" +
	"\n" +
	"error_type\x18\n" +
	" \x01(\tR\terrorType\"'\n" +
	"\tReportAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x03R\breceived\"V\n" +
	"\x11CreateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"<\n" +
	"\x12CreateUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.control.UserProtoR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x10ListUsersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"=\n" +
	"\x11ListUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.control.UserProtoR\x05users\"~\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1b\n" +
	"\x06active\x18\x04 \x01(\bH\x00R\x06active\x88\x01\x01B\t\n" +
	"\a_active\"<\n" +
	"\x12UpdateUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.control.UserProtoR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\";\n" +
	"\x0fAuthUserRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"P\n" +
	"\x10AuthUserResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12&\n" +
	"\x04user\x18\x02 \x01(\v2\x12.control.UserProtoR\x04user\"[\n" +
	"\rDNSAuditBatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\arecords\x18\x02 \x03(\v2\x17.control.DNSAuditRecordR\arecords\"\x9b\x01\n" +
	"\x0eDNSAuditRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"query_type\x18\x03 \x01(\tR\tqueryType\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\")\n" +
	"\vDNSAuditAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x03R\breceived\"\x98\x01\n" +
	"\x13TrafficQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06egress\x18\x03 \x01(\tR\x06egress\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"M\n" +
	"\x14TrafficQueryResponse\x125\n" +
	"\tsummaries\x18\x01 \x03(\v2\x17.control.TrafficSummaryR\tsummaries\"\xa9\x01\n" +
	"\x0eTrafficSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06egress\x18\x03 \x01(\tR\x06egress\x12\x19\n" +
	"\bbytes_up\x18\x04 \x01(\x03R\abytesUp\x12\x1d\n" +
	"\n" +
	"bytes_down\x18\x05 \x01(\x03R\tbytesDown\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count*\xaa\x01\n" +
	"\n" +
	"ConfigType\x12\x1b\n" +
	"\x17CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONFIG_TYPE_WHITELIST\x10\x01\x12\x17\n" +
	"\x13CONFIG_TYPE_ROUTING\x10\x02\x12\x15\n" +
	"\x11CONFIG_TYPE_USERS\x10\x03\x12\x18\n" +
	"\x14CONFIG_TYPE_ECH_KEYS\x10\x04\x12\x1a\n" +
	"\x16CONFIG_TYPE_EGRESS_IPS\x10\x052Q\n" +
	"\n" +
	"ConfigSync\x12C\n" +
	"\vWatchConfig\x12\x1b.control.WatchConfigRequest\x1a\x15.control.ConfigUpdate0\x012J\n" +
	"\n" +
	"NodeReport\x12<\n" +
	"\rReportTraffic\x12\x15.control.TrafficBatch\x1a\x12.control.ReportAck(\x012\x94\x03\n" +
	"\tUserAudit\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.control.CreateUserRequest\x1a\x1b.control.CreateUserResponse\x126\n" +
	"\aGetUser\x12\x17.control.GetUserRequest\x1a\x12.control.UserProto\x12B\n" +
	"\tListUsers\x12\x19.control.ListUsersRequest\x1a\x1a.control.ListUsersResponse\x12<\n" +
	"\n" +
	"UpdateUser\x12\x1a.control.UpdateUserRequest\x1a\x12.control.UserProto\x12E\n" +
	"\n" +
	"DeleteUser\x12\x1a.control.DeleteUserRequest\x1a\x1b.control.DeleteUserResponse\x12?\n" +
	"\bAuthUser\x12\x18.control.AuthUserRequest\x1a\x19.control.AuthUserResponse2G\n" +
	"\bDNSAudit\x12;\n" +
	"\tReportDNS\x12\x16.control.DNSAuditBatch\x1a\x14.control.DNSAuditAck(\x012[\n" +
	"\fTrafficQuery\x12K\n" +
	"\fQueryTraffic\x12\x1c.control.TrafficQueryRequest\x1a\x1d.control.TrafficQueryResponseB\x19Z\x17prism/api/proto/controlb\x06proto3"

var (
	file_api_proto_control_control_proto_rawDescOnce sync.Once
	file_api_proto_control_control_proto_rawDescData []byte
)

func file_api_proto_control_control_proto_rawDescGZIP() []byte {
	file_api_proto_control_control_proto_rawDescOnce.Do(func() {
		file_api_proto_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_control_proto_rawDesc), len(file_api_proto_control_control_proto_rawDesc)))
	})
	return file_api_proto_control_control_proto_rawDescData
}

var file_api_proto_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_proto_control_control_proto_goTypes = []any{
	(ConfigType)(0),              // 0: control.ConfigType
	(*WatchConfigRequest)(nil),   // 1: control.WatchConfigRequest
	(*ConfigUpdate)(nil),         // 2: control.ConfigUpdate
	(*WhitelistConfig)(nil),      // 3: control.WhitelistConfig
	(*RoutingConfig)(nil),        // 4: control.RoutingConfig
	(*EgressNodeProto)(nil),      // 5: control.EgressNodeProto
	(*RoutingRuleProto)(nil),     // 6: control.RoutingRuleProto
	(*CIDRMatch)(nil),            // 7: control.CIDRMatch
	(*GeoIPMatch)(nil),           // 8: control.GeoIPMatch
	(*UserList)(nil),             // 9: control.UserList
	(*UserProto)(nil),            // 10: control.UserProto
	(*ECHKeyConfig)(nil),         // 11: control.ECHKeyConfig
	(*EgressIPList)(nil),         // 12: control.EgressIPList
	(*TrafficBatch)(nil),         // 13: control.TrafficBatch
	(*TrafficRecord)(nil),        // 14: control.TrafficRecord
	(*ReportAck)(nil),            // 15: control.ReportAck
	(*CreateUserRequest)(nil),    // 16: control.CreateUserRequest
	(*CreateUserResponse)(nil),   // 17: control.CreateUserResponse
	(*GetUserRequest)(nil),       // 18: control.GetUserRequest
	(*ListUsersRequest)(nil),     // 19: control.ListUsersRequest
	(*ListUsersResponse)(nil),    // 20: control.ListUsersResponse
	(*UpdateUserRequest)(nil),    // 21: control.UpdateUserRequest
	(*UpdateUserResponse)(nil),   // 22: control.UpdateUserResponse
	(*DeleteUserRequest)(nil),    // 23: control.DeleteUserRequest
	(*DeleteUserResponse)(nil),   // 24: control.DeleteUserResponse
	(*AuthUserRequest)(nil),      // 25: control.AuthUserRequest
	(*AuthUserResponse)(nil),     // 26: control.AuthUserResponse
	(*DNSAuditBatch)(nil),        // 27: control.DNSAuditBatch
	(*DNSAuditRecord)(nil),       // 28: control.DNSAuditRecord
	(*DNSAuditAck)(nil),          // 29: control.DNSAuditAck
	(*TrafficQueryRequest)(nil),  // 30: control.TrafficQueryRequest
	(*TrafficQueryResponse)(nil), // 31: control.TrafficQueryResponse
	(*TrafficSummary)(nil),       // 32: control.TrafficSummary
}
var file_api_proto_control_control_proto_depIdxs = []int32{
	0,  // 0: control.ConfigUpdate.config_type:type_name -> control.ConfigType
	3,  // 1: control.ConfigUpdate.whitelist:type_name -> control.WhitelistConfig
	4,  // 2: control.ConfigUpdate.routing:type_name -> control.RoutingConfig
	9,  // 3: control.ConfigUpdate.users:type_name -> control.UserList
	11, // 4: control.ConfigUpdate.ech_keys:type_name -> control.ECHKeyConfig
	12, // 5: control.ConfigUpdate.egress_ips:type_name -> control.EgressIPList
	5,  // 6: control.RoutingConfig.nodes:type_name -> control.EgressNodeProto
	6,  // 7: control.RoutingConfig.rules:type_name -> control.RoutingRuleProto
	7,  // 8: control.RoutingRuleProto.cidr:type_name -> control.CIDRMatch
	8,  // 9: control.RoutingRuleProto.geoip:type_name -> control.GeoIPMatch
	10, // 10: control.UserList.users:type_name -> control.UserProto
	14, // 11: control.TrafficBatch.records:type_name -> control.TrafficRecord
	10, // 12: control.CreateUserResponse.user:type_name -> control.UserProto
	10, // 13: control.ListUsersResponse.users:type_name -> control.UserProto
	10, // 14: control.UpdateUserResponse.user:type_name -> control.UserProto
	10, // 15: control.AuthUserResponse.user:type_name -> control.UserProto
	28, // 16: control.DNSAuditBatch.records:type_name -> control.DNSAuditRecord
	32, // 17: control.TrafficQueryResponse.summaries:type_name -> control.TrafficSummary
	1,  // 18: control.ConfigSync.WatchConfig:input_type -> control.WatchConfigRequest
	13, // 19: control.NodeReport.ReportTraffic:input_type -> control.TrafficBatch
	16, // 20: control.UserAudit.CreateUser:input_type -> control.CreateUserRequest
	18, // 21: control.UserAudit.GetUser:input_type -> control.GetUserRequest
	19, // 22: control.UserAudit.ListUsers:input_type -> control.ListUsersRequest
	21, // 23: control.UserAudit.UpdateUser:input_type -> control.UpdateUserRequest
	23, // 24: control.UserAudit.DeleteUser:input_type -> control.DeleteUserRequest
	25, // 25: control.UserAudit.AuthUser:input_type -> control.AuthUserRequest
	27, // 26: control.DNSAudit.ReportDNS:input_type -> control.DNSAuditBatch
	30, // 27: control.TrafficQuery.QueryTraffic:input_type -> control.TrafficQueryRequest
	2,  // 28: control.ConfigSync.WatchConfig:output_type -> control.ConfigUpdate
	15, // 29: control.NodeReport.ReportTraffic:output_type -> control.ReportAck
	17, // 30: control.UserAudit.CreateUser:output_type -> control.CreateUserResponse
	10, // 31: control.UserAudit.GetUser:output_type -> control.UserProto
	20, // 32: control.UserAudit.ListUsers:output_type -> control.ListUsersResponse
	10, // 33: control.UserAudit.UpdateUser:output_type -> control.UserProto
	24, // 34: control.UserAudit.DeleteUser:output_type -> control.DeleteUserResponse
	26, // 35: control.UserAudit.AuthUser:output_type -> control.AuthUserResponse
	29, // 36: control.DNSAudit.ReportDNS:output_type -> control.DNSAuditAck
	31, // 37: control.TrafficQuery.QueryTraffic:output_type -> control.TrafficQueryResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_control_control_proto_init() }
func file_api_proto_control_control_proto_init() {
	if File_api_proto_control_control_proto != nil {
		return
	}
	file_api_proto_control_control_proto_msgTypes[1].OneofWrappers = []any{
		(*ConfigUpdate_Whitelist)(nil),
		(*ConfigUpdate_Routing)(nil),
		(*ConfigUpdate_Users)(nil),
		(*ConfigUpdate_EchKeys)(nil),
		(*ConfigUpdate_EgressIps)(nil),
	}
	file_api_proto_control_control_proto_msgTypes[5].OneofWrappers = []any{
		(*RoutingRuleProto_Domain)(nil),
		(*RoutingRuleProto_Cidr)(nil),
		(*RoutingRuleProto_Geoip)(nil),
		(*RoutingRuleProto_IsDefault)(nil),
	}
	file_api_proto_control_control_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_control_proto_rawDesc), len(file_api_proto_control_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_proto_control_control_proto_goTypes,
		DependencyIndexes: file_api_proto_control_control_proto_depIdxs,
		EnumInfos:         file_api_proto_control_control_proto_enumTypes,
		MessageInfos:      file_api_proto_control_control_proto_msgTypes,
	}.Build()
	File_api_proto_control_control_proto = out.File
	file_api_proto_control_control_proto_goTypes = nil
	file_api_proto_control_control_proto_depIdxs = nil
}
