// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/proto/control/control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSync_WatchConfig_FullMethodName = "/control.ConfigSync/WatchConfig"
)

// ConfigSyncClient is the client API for ConfigSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigSyncClient interface {
	// WatchConfig opens a server-streaming RPC. The controller pushes
	// ConfigUpdate messages whenever whitelist, routing rules, users,
	// ECH keys, or egress IP lists change.
	WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error)
}

type configSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncClient(cc grpc.ClientConnInterface) ConfigSyncClient {
	return &configSyncClient{cc}
}

func (c *configSyncClient) WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSync_ServiceDesc.Streams[0], ConfigSync_WatchConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfigRequest, ConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_WatchConfigClient = grpc.ServerStreamingClient[ConfigUpdate]

// ConfigSyncServer is the server API for ConfigSync service.
// All implementations must embed UnimplementedConfigSyncServer
// for forward compatibility.
type ConfigSyncServer interface {
	// WatchConfig opens a server-streaming RPC. The controller pushes
	// ConfigUpdate messages whenever whitelist, routing rules, users,
	// ECH keys, or egress IP lists change.
	WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[ConfigUpdate]) error
	mustEmbedUnimplementedConfigSyncServer()
}

// UnimplementedConfigSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServer struct{}

func (UnimplementedConfigSyncServer) WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[ConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedConfigSyncServer) mustEmbedUnimplementedConfigSyncServer() {}
func (UnimplementedConfigSyncServer) testEmbeddedByValue()                    {}

// UnsafeConfigSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServer will
// result in compilation errors.
type UnsafeConfigSyncServer interface {
	mustEmbedUnimplementedConfigSyncServer()
}

func RegisterConfigSyncServer(s grpc.ServiceRegistrar, srv ConfigSyncServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSync_ServiceDesc, srv)
}

func _ConfigSync_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigSyncServer).WatchConfig(m, &grpc.GenericServerStream[WatchConfigRequest, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_WatchConfigServer = grpc.ServerStreamingServer[ConfigUpdate]

// ConfigSync_ServiceDesc is the grpc.ServiceDesc for ConfigSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.ConfigSync",
	HandlerType: (*ConfigSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _ConfigSync_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/control/control.proto",
}

const (
	NodeReport_ReportTraffic_FullMethodName = "/control.NodeReport/ReportTraffic"
)

// NodeReportClient is the client API for NodeReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeReportClient interface {
	// ReportTraffic accepts a client-streaming RPC of traffic metric batches.
	ReportTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TrafficBatch, ReportAck], error)
}

type nodeReportClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeReportClient(cc grpc.ClientConnInterface) NodeReportClient {
	return &nodeReportClient{cc}
}

func (c *nodeReportClient) ReportTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TrafficBatch, ReportAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeReport_ServiceDesc.Streams[0], NodeReport_ReportTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrafficBatch, ReportAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeReport_ReportTrafficClient = grpc.ClientStreamingClient[TrafficBatch, ReportAck]

// NodeReportServer is the server API for NodeReport service.
// All implementations must embed UnimplementedNodeReportServer
// for forward compatibility.
type NodeReportServer interface {
	// ReportTraffic accepts a client-streaming RPC of traffic metric batches.
	ReportTraffic(grpc.ClientStreamingServer[TrafficBatch, ReportAck]) error
	mustEmbedUnimplementedNodeReportServer()
}

// UnimplementedNodeReportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeReportServer struct{}

func (UnimplementedNodeReportServer) ReportTraffic(grpc.ClientStreamingServer[TrafficBatch, ReportAck]) error {
	return status.Error(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedNodeReportServer) mustEmbedUnimplementedNodeReportServer() {}
func (UnimplementedNodeReportServer) testEmbeddedByValue()                    {}

// UnsafeNodeReportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeReportServer will
// result in compilation errors.
type UnsafeNodeReportServer interface {
	mustEmbedUnimplementedNodeReportServer()
}

func RegisterNodeReportServer(s grpc.ServiceRegistrar, srv NodeReportServer) {
	// If the following call panics, it indicates UnimplementedNodeReportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeReport_ServiceDesc, srv)
}

func _NodeReport_ReportTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeReportServer).ReportTraffic(&grpc.GenericServerStream[TrafficBatch, ReportAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeReport_ReportTrafficServer = grpc.ClientStreamingServer[TrafficBatch, ReportAck]

// NodeReport_ServiceDesc is the grpc.ServiceDesc for NodeReport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeReport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.NodeReport",
	HandlerType: (*NodeReportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportTraffic",
			Handler:       _NodeReport_ReportTraffic_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/control/control.proto",
}

const (
	UserAudit_CreateUser_FullMethodName = "/control.UserAudit/CreateUser"
	UserAudit_GetUser_FullMethodName    = "/control.UserAudit/GetUser"
	UserAudit_ListUsers_FullMethodName  = "/control.UserAudit/ListUsers"
	UserAudit_UpdateUser_FullMethodName = "/control.UserAudit/UpdateUser"
	UserAudit_DeleteUser_FullMethodName = "/control.UserAudit/DeleteUser"
	UserAudit_AuthUser_FullMethodName   = "/control.UserAudit/AuthUser"
)

// UserAuditClient is the client API for UserAudit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAuditClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProto, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserProto, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error)
}

type userAuditClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAuditClient(cc grpc.ClientConnInterface) UserAuditClient {
	return &userAuditClient{cc}
}

func (c *userAuditClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserAudit_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuditClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProto)
	err := c.cc.Invoke(ctx, UserAudit_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuditClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UserAudit_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuditClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProto)
	err := c.cc.Invoke(ctx, UserAudit_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuditClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, UserAudit_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuditClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AuthUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUserResponse)
	err := c.cc.Invoke(ctx, UserAudit_AuthUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuditServer is the server API for UserAudit service.
// All implementations must embed UnimplementedUserAuditServer
// for forward compatibility.
type UserAuditServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserProto, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UserProto, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error)
	mustEmbedUnimplementedUserAuditServer()
}

// UnimplementedUserAuditServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAuditServer struct{}

func (UnimplementedUserAuditServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserAuditServer) GetUser(context.Context, *GetUserRequest) (*UserProto, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserAuditServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedUserAuditServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserProto, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserAuditServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserAuditServer) AuthUser(context.Context, *AuthUserRequest) (*AuthUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthUser not implemented")
}
func (UnimplementedUserAuditServer) mustEmbedUnimplementedUserAuditServer() {}
func (UnimplementedUserAuditServer) testEmbeddedByValue()                   {}

// UnsafeUserAuditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAuditServer will
// result in compilation errors.
type UnsafeUserAuditServer interface {
	mustEmbedUnimplementedUserAuditServer()
}

func RegisterUserAuditServer(s grpc.ServiceRegistrar, srv UserAuditServer) {
	// If the following call panics, it indicates UnimplementedUserAuditServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAudit_ServiceDesc, srv)
}

func _UserAudit_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAudit_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAudit_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAudit_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAudit_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAudit_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuditServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAudit_AuthUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuditServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAudit_ServiceDesc is the grpc.ServiceDesc for UserAudit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAudit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.UserAudit",
	HandlerType: (*UserAuditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserAudit_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserAudit_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserAudit_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserAudit_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserAudit_DeleteUser_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _UserAudit_AuthUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/control/control.proto",
}

const (
	DNSAudit_ReportDNS_FullMethodName = "/control.DNSAudit/ReportDNS"
)

// DNSAuditClient is the client API for DNSAudit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DNSAuditClient interface {
	ReportDNS(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNSAuditBatch, DNSAuditAck], error)
}

type dNSAuditClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSAuditClient(cc grpc.ClientConnInterface) DNSAuditClient {
	return &dNSAuditClient{cc}
}

func (c *dNSAuditClient) ReportDNS(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNSAuditBatch, DNSAuditAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DNSAudit_ServiceDesc.Streams[0], DNSAudit_ReportDNS_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DNSAuditBatch, DNSAuditAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DNSAudit_ReportDNSClient = grpc.ClientStreamingClient[DNSAuditBatch, DNSAuditAck]

// DNSAuditServer is the server API for DNSAudit service.
// All implementations must embed UnimplementedDNSAuditServer
// for forward compatibility.
type DNSAuditServer interface {
	ReportDNS(grpc.ClientStreamingServer[DNSAuditBatch, DNSAuditAck]) error
	mustEmbedUnimplementedDNSAuditServer()
}

// UnimplementedDNSAuditServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSAuditServer struct{}

func (UnimplementedDNSAuditServer) ReportDNS(grpc.ClientStreamingServer[DNSAuditBatch, DNSAuditAck]) error {
	return status.Error(codes.Unimplemented, "method ReportDNS not implemented")
}
func (UnimplementedDNSAuditServer) mustEmbedUnimplementedDNSAuditServer() {}
func (UnimplementedDNSAuditServer) testEmbeddedByValue()                  {}

// UnsafeDNSAuditServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSAuditServer will
// result in compilation errors.
type UnsafeDNSAuditServer interface {
	mustEmbedUnimplementedDNSAuditServer()
}

func RegisterDNSAuditServer(s grpc.ServiceRegistrar, srv DNSAuditServer) {
	// If the following call panics, it indicates UnimplementedDNSAuditServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSAudit_ServiceDesc, srv)
}

func _DNSAudit_ReportDNS_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DNSAuditServer).ReportDNS(&grpc.GenericServerStream[DNSAuditBatch, DNSAuditAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DNSAudit_ReportDNSServer = grpc.ClientStreamingServer[DNSAuditBatch, DNSAuditAck]

// DNSAudit_ServiceDesc is the grpc.ServiceDesc for DNSAudit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSAudit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.DNSAudit",
	HandlerType: (*DNSAuditServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportDNS",
			Handler:       _DNSAudit_ReportDNS_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/control/control.proto",
}

const (
	TrafficQuery_QueryTraffic_FullMethodName = "/control.TrafficQuery/QueryTraffic"
)

// TrafficQueryClient is the client API for TrafficQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficQueryClient interface {
	QueryTraffic(ctx context.Context, in *TrafficQueryRequest, opts ...grpc.CallOption) (*TrafficQueryResponse, error)
}

type trafficQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficQueryClient(cc grpc.ClientConnInterface) TrafficQueryClient {
	return &trafficQueryClient{cc}
}

func (c *trafficQueryClient) QueryTraffic(ctx context.Context, in *TrafficQueryRequest, opts ...grpc.CallOption) (*TrafficQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficQueryResponse)
	err := c.cc.Invoke(ctx, TrafficQuery_QueryTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficQueryServer is the server API for TrafficQuery service.
// All implementations must embed UnimplementedTrafficQueryServer
// for forward compatibility.
type TrafficQueryServer interface {
	QueryTraffic(context.Context, *TrafficQueryRequest) (*TrafficQueryResponse, error)
	mustEmbedUnimplementedTrafficQueryServer()
}

// UnimplementedTrafficQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficQueryServer struct{}

func (UnimplementedTrafficQueryServer) QueryTraffic(context.Context, *TrafficQueryRequest) (*TrafficQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTraffic not implemented")
}
func (UnimplementedTrafficQueryServer) mustEmbedUnimplementedTrafficQueryServer() {}
func (UnimplementedTrafficQueryServer) testEmbeddedByValue()                      {}

// UnsafeTrafficQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficQueryServer will
// result in compilation errors.
type UnsafeTrafficQueryServer interface {
	mustEmbedUnimplementedTrafficQueryServer()
}

func RegisterTrafficQueryServer(s grpc.ServiceRegistrar, srv TrafficQueryServer) {
	// If the following call panics, it indicates UnimplementedTrafficQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficQuery_ServiceDesc, srv)
}

func _TrafficQuery_QueryTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficQueryServer).QueryTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrafficQuery_QueryTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficQueryServer).QueryTraffic(ctx, req.(*TrafficQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficQuery_ServiceDesc is the grpc.ServiceDesc for TrafficQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.TrafficQuery",
	HandlerType: (*TrafficQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTraffic",
			Handler:    _TrafficQuery_QueryTraffic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/control/control.proto",
}
